[workspace]
members = [
"firmware",
"crates/*"
]
resolver = "3"

[workspace.dependencies]
defmt = "1.0.1"
embassy-sync = { version = "0.7.2", features = ["defmt"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false

[patch.crates-io]
rs-matter = { path = "../rs-matter/rs-matter" }

# update to embedded-io 0.7 in embassy sync
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "5dd8511a87096f664ca486c8a3c637367a15419a" }
embassy-net = { git = "https://github.com/embassy-rs/embassy.git", rev = "5dd8511a87096f664ca486c8a3c637367a15419a" }
embassy-net-driver = { git = "https://github.com/embassy-rs/embassy.git", rev = "5dd8511a87096f664ca486c8a3c637367a15419a" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "5dd8511a87096f664ca486c8a3c637367a15419a" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "5dd8511a87096f664ca486c8a3c637367a15419a" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy.git", rev = "5dd8511a87096f664ca486c8a3c637367a15419a" }
embassy-time-queue-utils = { git = "https://github.com/embassy-rs/embassy.git", rev = "5dd8511a87096f664ca486c8a3c637367a15419a" }

# esp-hal crates
esp-rom-sys = { git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896" }
esp-sync = { git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896" }
esp-hal = { git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896" }
esp-radio = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
esp-storage = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
esp-alloc = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
esp-backtrace = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
esp-println = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
esp-rtos = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
esp-bootloader-esp-idf = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
esp-metadata-generated = {git = "https://github.com/esp-rs/esp-hal.git", rev = "d7e307beeeb3a2aa72200f8fff3902869ef50896"}
