[settings]
watch_path = "/home/arlyon/Downloads"
recursive = false

[formats.External]
format = "kicad"
output_path = "/home/arlyon/Programming/rust-matter-led/hardware/external"

[profile]
username = "arlyon@me.com"
password = "E#3$ndR%VnuW$6m"
